name: master-tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r requirements.txt --system
      - name: lint and test
        run: |
          echo Checking formatting...
          ruff format --check .
          echo Checking linting...
          ruff check  .
          echo Running tests...
          pytest
