name: nosetests

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose
        pip install -r requirements.txt
    - name: Test with nose on windows
      run: nosetests -v -A '!fails_on_windows' .
      if: matrix.os == 'windows-latest'
    - name: Test with nose on ubuntu and macOS
      run: nosetests -v .
      if: matrix.os != 'windows-latest'
